# Generated by Django 5.2.4 on 2025-08-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="price",
            field=models.IntegerField(default=1650, help_text="Price in UGX"),
        ),
    ]
