# Generated by Django 5.2.4 on 2025-08-06 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_stock_id_alter_stock_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="date_registered",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="farmer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Approval status",
                max_length=10,
            ),
        ),
    ]
