# Generated by Django 5.2.4 on 2025-08-06 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_farmer_date_registered_farmer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="chickrequest",
            name="sales_authorized",
            field=models.BooleanField(
                default=False, help_text="Sales agent authorized the sale"
            ),
        ),
        migrations.AddField(
            model_name="chickrequest",
            name="sales_authorized_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Sales agent who authorized the sale",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chickrequest",
            name="sales_authorized_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when sale was authorized", null=True
            ),
        ),
        migrations.AlterField(
            model_name="chickrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("sold", "Sold"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
